"use strict";(()=>{var e={};e.id=826,e.ids=[826],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8687:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>y,patchFetch:()=>b,requestAsyncStorage:()=>O,routeModule:()=>I,serverHooks:()=>w,staticGenerationAsyncStorage:()=>R});var a={};r.r(a),r.d(a,{POST:()=>A,dynamic:()=>f,runtime:()=>_});var n=r(9303),i=r(8716),o=r(670),s=r(7070),l=r(5748);let c=process.env.OPENAI_RANK_MODEL||"gpt-4o-mini";function u(e){return Number.isFinite(e)?Math.min(100,Math.max(0,Math.round(e))):50}function d(e){let t=e.toLowerCase(),r=40;for(let e of["war","attack","election","inflation","federal reserve","interest rate","policy","regulation","earnings","layoff","ai","security","breach","outage"])t.includes(e)&&(r+=10);for(let e of["launch","update","product","partnership","acquisition","funding","startup","chip","market"])t.includes(e)&&(r+=4);return{score:u(r),reason:"Heuristic ranking used because LLM output was unavailable.",usedFallback:!0}}async function E(e){let t=process.env.OPENAI_API_KEY;if(!t)return{...d(e.title),model:"heuristic-fallback"};try{var r;let a=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({model:c,temperature:.1,response_format:{type:"json_object"},messages:[{role:"system",content:"You rank news importance for a general reader. Return JSON only with keys: importanceScore (0-100 number) and reason (short string)."},{role:"user",content:`Title: ${e.title}
Source: ${e.source}
PublishedAt: ${(r=e.published_at)instanceof Date?r.toISOString():r}
Task: Score how important this article is to read now.`}]})});if(!a.ok)throw Error(`OpenAI request failed with ${a.status}`);let n=await a.json(),i=n.choices?.[0]?.message?.content;if(!i)throw Error("OpenAI response did not include content");let o=JSON.parse(i);return{score:function(e){for(let t of[e.importanceScore,e.importance_score,e.score]){if("number"==typeof t)return u(t);if("string"==typeof t&&""!==t.trim()){let e=Number(t);if(!Number.isNaN(e))return u(e)}}throw Error("Missing score in LLM payload")}(o),reason:function(e){let t=e.reason;return"string"==typeof t?function(e){let t=e.trim();return t?t.length>220?`${t.slice(0,217)}...`:t:"High-level importance ranking based on article metadata."}(t):"Importance ranking generated by LLM."}(o),model:c,usedFallback:!1}}catch(t){return console.error("LLM ranking failed, using heuristic fallback:",t),{...d(e.title),model:"heuristic-fallback"}}}async function T(e){let t=(0,l.z)(),r=0,a=0,n=0,i=[];for(let o=0;o<e.length;o+=4){let s=e.slice(o,o+4);for(let e of(await Promise.all(s.map(async e=>{try{let t=await E(e);return{candidate:e,ranked:t,error:null}}catch(t){return{candidate:e,ranked:null,error:t}}})))){if(!e.ranked){n++,console.error(`Failed to rank item ${e.candidate.id}:`,e.error);continue}let o=new Date().toISOString();(await t`
        SELECT 1 FROM feed_items WHERE id = ${e.candidate.id} LIMIT 1
      `).length>0&&await t`
          INSERT INTO item_rankings (item_id, importance_score, reason, model, ranked_at)
          VALUES (
            ${e.candidate.id},
            ${e.ranked.score},
            ${e.ranked.reason},
            ${e.ranked.model},
            ${o}
          )
          ON CONFLICT (item_id) DO UPDATE SET
            importance_score = EXCLUDED.importance_score,
            reason = EXCLUDED.reason,
            model = EXCLUDED.model,
            ranked_at = EXCLUDED.ranked_at
        `,i.push({itemId:e.candidate.id,importanceScore:e.ranked.score,reason:e.ranked.reason,model:e.ranked.model,rankedAt:o,usedFallback:e.ranked.usedFallback}),e.ranked.usedFallback?a++:r++}}return{processed:e.length,llmRanked:r,fallbackRanked:a,failed:n,model:process.env.OPENAI_API_KEY?c:"heuristic-fallback",rankings:i}}async function p(e){let t=(0,l.z)();return T(await t`
    SELECT id, title, source, published_at
    FROM feed_items
    ORDER BY created_at DESC
    LIMIT ${Math.max(1,Math.min(e,100))}
  `)}async function m(e,t){let r=e.slice(0,Math.max(1,Math.min(t,100))),a=new Set,n=[];for(let e of r)!e.id||a.has(e.id)||(a.add(e.id),n.push({id:e.id,title:e.title,source:e.source,published_at:e.publishedAt}));return T(n)}let f="force-dynamic",_="nodejs",N=["REUTERS","THE_VERGE","TECHCRUNCH"],h=!1,g=!1,L=0;async function S(){h||(await (0,l.D)(),h=!0)}function k(e,t){return s.NextResponse.json(e,{...t,headers:{...t?.headers,"Cache-Control":"no-store"}})}async function A(e){if(g)return k({ok:!1,error:"Ranking is already running. Please wait."},{status:409});let t=Date.now(),r=t-L;if(r<45e3){let e=Math.ceil((45e3-r)/1e3);return k({ok:!1,error:`Please wait ${e}s before ranking again.`,retryAfterSeconds:e},{status:429,headers:{"Retry-After":String(e)}})}let a=20,n=[];try{var i;let t=await e.json(),r=(i=t?.topN,void 0===i?20:"number"!=typeof i||!Number.isInteger(i)||i<1||i>100?null:i);if(null===r)return k({ok:!1,error:"topN must be an integer between 1 and 100"},{status:400});a=r,n=function(e,t){if(!Array.isArray(e))return[];let r=[],a=new Set;for(let n of e){if(r.length>=t)break;if(!n||"object"!=typeof n)continue;let e=n.id,i=n.title,o=n.source,s=n.publishedAt;"string"==typeof e&&"string"==typeof i&&"string"==typeof o&&"string"==typeof s&&e.trim()&&i.trim()&&N.includes(o)&&(a.has(e)||(a.add(e),r.push({id:e.trim(),title:i.trim(),source:o,publishedAt:s.trim()})))}return r}(t?.items,a)}catch{}g=!0,L=t;try{await S();let e=await p(a),t=!1;0===e.processed&&n.length>0&&(e=await m(n,a),t=!0);let r=0===e.processed?"No articles available to rank.":t?`Ranked ${e.processed} loaded articles`:`Ranked ${e.processed} newest articles`;return k({ok:!0,topN:a,usedProvidedItems:t,...e,message:r})}catch(e){return console.error("Manual rank error:",e),k({ok:!1,error:"Article ranking failed"},{status:500})}finally{g=!1}}let I=new n.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/trigger-rank/route",pathname:"/api/trigger-rank",filename:"route",bundlePath:"app/api/trigger-rank/route"},resolvedPagePath:"/Users/jeganprakash/Creative/news-rss-feed/src/app/api/trigger-rank/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:O,staticGenerationAsyncStorage:R,serverHooks:w}=I,y="/api/trigger-rank/route";function b(){return(0,o.patchFetch)({serverHooks:w,staticGenerationAsyncStorage:R})}},5748:(e,t,r)=>{r.d(t,{D:()=>l,z:()=>s});var a=r(2237);let n=null,i=!1,o=null;function s(){return n||(n=(0,a.qn)(function(){let e=process.env.DATABASE_URL;if(!e){let e=["POSTGRES_URL","POSTGRES_PRISMA_URL","NEON_DATABASE_URL","DATABASE_PATH"].filter(e=>!!process.env[e]),t=e.length>0?` Found ${e.join(", ")} but this app now requires DATABASE_URL explicitly to avoid connecting to the wrong database.`:"";throw Error(`DATABASE_URL is not configured.${t}`)}return e}())),n}async function l(){if(i)return;if(o)return o;let e=s();return o=(async()=>{await e`
      CREATE TABLE IF NOT EXISTS feed_items (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        source TEXT NOT NULL,
        published_at TIMESTAMPTZ NOT NULL,
        url_original TEXT,
        url_source TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        normalized_title TEXT NOT NULL
      )
    `,await e`
      CREATE INDEX IF NOT EXISTS idx_created_at ON feed_items(created_at DESC)
    `,await e`
      CREATE INDEX IF NOT EXISTS idx_source ON feed_items(source)
    `,await e`
      CREATE INDEX IF NOT EXISTS idx_url_original ON feed_items(url_original)
    `,await e`
      CREATE INDEX IF NOT EXISTS idx_normalized_title ON feed_items(normalized_title)
    `,await e`
      CREATE TABLE IF NOT EXISTS source_metadata (
        source TEXT PRIMARY KEY,
        last_fetch_time TIMESTAMPTZ,
        last_fetch_status TEXT,
        last_error TEXT
      )
    `,await e`
      INSERT INTO source_metadata (source, last_fetch_time, last_fetch_status, last_error)
      VALUES
        ('REUTERS', NULL, NULL, NULL),
        ('THE_VERGE', NULL, NULL, NULL),
        ('TECHCRUNCH', NULL, NULL, NULL)
      ON CONFLICT (source) DO NOTHING
    `,await e`
      CREATE TABLE IF NOT EXISTS item_rankings (
        item_id TEXT PRIMARY KEY,
        importance_score DOUBLE PRECISION NOT NULL,
        reason TEXT,
        model TEXT NOT NULL,
        ranked_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT fk_item_rankings_item
          FOREIGN KEY (item_id) REFERENCES feed_items(id) ON DELETE CASCADE
      )
    `,await e`
      CREATE INDEX IF NOT EXISTS idx_item_rankings_score ON item_rankings(importance_score DESC)
    `,await e`
      CREATE INDEX IF NOT EXISTS idx_item_rankings_ranked_at ON item_rankings(ranked_at DESC)
    `,i=!0})().finally(()=>{o=null})}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[276,415],()=>r(8687));module.exports=a})();