import { getDb } from './db';
import type { FeedSource } from '@/types/feed';

const DEFAULT_RANK_MODEL = process.env.OPENAI_RANK_MODEL || 'gpt-4o-mini';
const RANK_BATCH_SIZE = 4;

interface RankCandidate {
  id: string;
  title: string;
  source: FeedSource;
  published_at: string;
}

interface RankOutput {
  score: number;
  reason: string;
  model: string;
  usedFallback: boolean;
}

export interface RankBatchResult {
  processed: number;
  llmRanked: number;
  fallbackRanked: number;
  failed: number;
  model: string;
}

function clampScore(value: number): number {
  if (!Number.isFinite(value)) {
    return 50;
  }
  return Math.min(100, Math.max(0, Math.round(value)));
}

function truncateReason(reason: string): string {
  const trimmed = reason.trim();
  if (!trimmed) {
    return 'High-level importance ranking based on article metadata.';
  }
  return trimmed.length > 220 ? `${trimmed.slice(0, 217)}...` : trimmed;
}

function heuristicRank(title: string): Omit<RankOutput, 'model'> {
  const normalized = title.toLowerCase();

  const highImpactTerms = [
    'war',
    'attack',
    'election',
    'inflation',
    'federal reserve',
    'interest rate',
    'policy',
    'regulation',
    'earnings',
    'layoff',
    'ai',
    'security',
    'breach',
    'outage',
  ];
  const mediumImpactTerms = [
    'launch',
    'update',
    'product',
    'partnership',
    'acquisition',
    'funding',
    'startup',
    'chip',
    'market',
  ];

  let score = 40;
  for (const term of highImpactTerms) {
    if (normalized.includes(term)) score += 10;
  }
  for (const term of mediumImpactTerms) {
    if (normalized.includes(term)) score += 4;
  }

  return {
    score: clampScore(score),
    reason: 'Heuristic ranking used because LLM output was unavailable.',
    usedFallback: true,
  };
}

function normalizeLlmScore(payload: Record<string, unknown>): number {
  const candidates = [
    payload.importanceScore,
    payload.importance_score,
    payload.score,
  ];

  for (const candidate of candidates) {
    if (typeof candidate === 'number') {
      return clampScore(candidate);
    }
    if (typeof candidate === 'string' && candidate.trim() !== '') {
      const parsed = Number(candidate);
      if (!Number.isNaN(parsed)) return clampScore(parsed);
    }
  }

  throw new Error('Missing score in LLM payload');
}

function normalizeLlmReason(payload: Record<string, unknown>): string {
  const reason = payload.reason;
  if (typeof reason === 'string') {
    return truncateReason(reason);
  }
  return 'Importance ranking generated by LLM.';
}

async function rankWithLlm(candidate: RankCandidate): Promise<RankOutput> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    const fallback = heuristicRank(candidate.title);
    return { ...fallback, model: 'heuristic-fallback' };
  }

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: DEFAULT_RANK_MODEL,
        temperature: 0.1,
        response_format: { type: 'json_object' },
        messages: [
          {
            role: 'system',
            content:
              'You rank news importance for a general reader. Return JSON only with keys: importanceScore (0-100 number) and reason (short string).',
          },
          {
            role: 'user',
            content: [
              `Title: ${candidate.title}`,
              `Source: ${candidate.source}`,
              `PublishedAt: ${candidate.published_at}`,
              'Task: Score how important this article is to read now.',
            ].join('\n'),
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI request failed with ${response.status}`);
    }

    const payload = (await response.json()) as {
      choices?: Array<{ message?: { content?: string | null } }>;
    };
    const content = payload.choices?.[0]?.message?.content;
    if (!content) throw new Error('OpenAI response did not include content');

    const parsed = JSON.parse(content) as Record<string, unknown>;
    return {
      score: normalizeLlmScore(parsed),
      reason: normalizeLlmReason(parsed),
      model: DEFAULT_RANK_MODEL,
      usedFallback: false,
    };
  } catch (error: unknown) {
    console.error('LLM ranking failed, using heuristic fallback:', error);
    const fallback = heuristicRank(candidate.title);
    return { ...fallback, model: 'heuristic-fallback' };
  }
}

/**
 * Rank the top N newest feed items and persist their importance scores.
 */
export async function rankTopNewestArticles(limit: number): Promise<RankBatchResult> {
  const db = getDb();
  const safeLimit = Math.max(1, Math.min(limit, 100));

  const candidates = db
    .prepare(
      `SELECT id, title, source, published_at
       FROM feed_items
       ORDER BY created_at DESC
       LIMIT ?`
    )
    .all(safeLimit) as RankCandidate[];

  const upsertStmt = db.prepare(
    `INSERT INTO item_rankings (item_id, importance_score, reason, model, ranked_at)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT(item_id) DO UPDATE SET
       importance_score = excluded.importance_score,
       reason = excluded.reason,
       model = excluded.model,
       ranked_at = excluded.ranked_at`
  );

  let llmRanked = 0;
  let fallbackRanked = 0;
  let failed = 0;

  for (let i = 0; i < candidates.length; i += RANK_BATCH_SIZE) {
    const batch = candidates.slice(i, i + RANK_BATCH_SIZE);
    const batchResults = await Promise.all(
      batch.map(async (candidate) => {
        try {
          const ranked = await rankWithLlm(candidate);
          return { candidate, ranked, error: null as unknown };
        } catch (error: unknown) {
          return { candidate, ranked: null, error };
        }
      })
    );

    for (const result of batchResults) {
      if (!result.ranked) {
        failed++;
        console.error(`Failed to rank item ${result.candidate.id}:`, result.error);
        continue;
      }

      upsertStmt.run(
        result.candidate.id,
        result.ranked.score,
        result.ranked.reason,
        result.ranked.model,
        new Date().toISOString()
      );

      if (result.ranked.usedFallback) {
        fallbackRanked++;
      } else {
        llmRanked++;
      }
    }
  }

  return {
    processed: candidates.length,
    llmRanked,
    fallbackRanked,
    failed,
    model: process.env.OPENAI_API_KEY ? DEFAULT_RANK_MODEL : 'heuristic-fallback',
  };
}
